### ISSUE TITLE
CRON SendAlerts : can't use `parseArticles` hook

### ISSUE THREAD

**Issue by ChipsVII** [Web-Ex-Machina/contao-job-offers#13]
The `parseArticles` hooks expects an instance of `\Contao\Module` as its 3rd parameter, but we cannot provide any at this moment.
So the hook usage is disabled until a solution is found.

**Comment by LupusVII** [comment]
It was a "dumb" copy and paste from Contao code, you can trash it when you have the opportunity.

**Comment by ChipsVII** [comment]
Trashed in `2.x` branch
