### ISSUE TITLE
move assets version to higher level

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-job-offers#18]
for now, modules offersList and offersAlert make use of assets and inject them with Combiner which requires a version number for cache management. 
![image](https://github.com/Web-Ex-Machina/contao-offers/assets/28646786/9192e67a-accd-41fd-b636-3e60224fc766)

$strVersion should be defined once, and at a higher level to avoid having to go fishing each update

**Comment by SeptimusVII** [comment]
could use bundle version as combiner version for assets

**Comment by LupusVII** [comment]
Fixed in https://github.com/Web-Ex-Machina/contao-offers/commit/5403fdd11f8fd6b9072af8819d603a505ed66d21
