### ISSUE TITLE
Exception triggers an error in Contao Manager

### ISSUE THREAD

**Issue by LupusVII** [Web-Ex-Machina/contao-job-offers#22]
This file: `src\EventListener\LoadDataContainerListener.php`
This line (43): `System::log(vsprintf($GLOBALS['TL_LANG']['WEM']['OFFERS']['ERROR']['generic'], [$e->getMessage(), $e->getTrace()]), __METHOD__, 'WEM_OFFERS');`

Trigger the error below:
![image](https://github.com/Web-Ex-Machina/contao-offers/assets/4595194/a5d159bc-dce1-4fda-adb8-828b45b7f713)

**Comment by LupusVII** [comment]
I do not understand the issue though, because the translations seems to exist. Maybe `default.xlf` file is not load in the Contao Manager context?

**Comment by NodokaMurmevent** [comment]
Fixed by https://github.com/Web-Ex-Machina/contao-offers/commit/59e422b4153cb20ec5f8586e4b493a09a3c72794
