### ISSUE TITLE
Contao-backend

### ISSUE THREAD

**Issue by SeptimusVII** [Web-Ex-Machina/contao-job-offers#6]
- [x] #7

![image](https://user-images.githubusercontent.com/28646786/218506521-ee08716f-17fb-4910-bc53-54d99a093272.png)
![image](https://user-images.githubusercontent.com/28646786/218506603-ea732448-4159-47a1-a249-8639a8f7dcd0.png)

- [x] job's fields not relevant in a generic context. Should be made from custom attributes 
![image](https://user-images.githubusercontent.com/28646786/218507994-5ecf9550-fdac-4cad-9d24-3d1393d0fb06.png)

- [x] #8
![image](https://user-images.githubusercontent.com/28646786/218508534-314f3ef0-c235-4e41-bfaa-820e1da77692.png)

- [x] this field is not planned in module's zoning, and doesn't seem useful to me.
![image](https://user-images.githubusercontent.com/28646786/218509480-ac91b027-9a9e-496d-ac84-5cf587f9161b.png)

- [x] #9
![image](https://user-images.githubusercontent.com/28646786/218509780-5c9a1650-a3ea-4ca1-920a-c709329fe726.png)

- [x] can we have a blnDisplayAttributes, and a blnDisplayPictures, next to the blnDisplayText field 
![image](https://user-images.githubusercontent.com/28646786/218529316-dba52c5d-058a-4d18-a5c8-5efcc00a941b.png)

- [x] can't dupplicate an offer: `An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '='' WHERE id='6'' at line 1`

**Comment by SeptimusVII** [comment]
@LupusVII

**Comment by LupusVII** [comment]
The duplication issue is linked to the first SQL error.

**Comment by LupusVII** [comment]
For the contact picture, since it is not mandatory, should we leave it for people who might use it?

**Comment by SeptimusVII** [comment]
> For the contact picture, since it is not mandatory, should we leave it for people who might use it?

since it is not a generic type of field, my go to would be to trash it. If someone  happen to need it, it should be a module override

**Comment by LupusVII** [comment]
> > For the contact picture, since it is not mandatory, should we leave it for people who might use it?
> 
> since it is not a generic type of field, my go to would be to trash it. If someone happen to need it, it should be a module override

Trash it is then

**Comment by LupusVII** [comment]
Done in https://github.com/Web-Ex-Machina/contao-offers/releases/tag/2.0.0
