### ISSUE TITLE
Field "file" clarification

### ISSUE THREAD

**Issue by LupusVII** [Web-Ex-Machina/contao-job-offers#8]
"This field allow every type of file. Tt's okay for a downlowdable text file like a pdf, but for pictures, sizing fields would be needed. We may want to have a slider of multiple pictures, like leboncoin ? if so, take the smartgear.fr's tabs/slider image configuration fields as reference"

@SeptimusVII Should we split this into two fields: pictures / files ?
And make those fields not mandatory since not all kind of offers requires pictures nor files?

**Comment by SeptimusVII** [comment]
> "This field allow every type of file. Tt's okay for a downlowdable text file like a pdf, but for pictures, sizing fields would be needed. We may want to have a slider of multiple pictures, like leboncoin ? if so, take the smartgear.fr's tabs/slider image configuration fields as reference"
> 
> @SeptimusVII Should we split this into two fields: pictures / files ? And make those fields not mandatory since not all kind of offers requires pictures nor files?

yes for spliting into two fields, not mandatory

**Comment by SeptimusVII** [comment]
@LupusVII this issue does not look like it's resolved. Confusion between branches `origin/issue-8-Field_file_clarification` and `origin/issue-6-Contao-backend` may have been made, as `origin/issue-6-Contao-backend` seems to hold answers to this issue, but hasn't been merged
![image](https://github.com/Web-Ex-Machina/contao-offers/assets/28646786/3155734f-d918-416a-81bc-2b76b25284d7)

**Comment by LupusVII** [comment]
Fixed with https://github.com/Web-Ex-Machina/contao-offers/releases/tag/2.0.0
